[package]
name = "architecture-quantumforge-software"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.96"
async-stream = "0.3.6"
async-trait = "0.1.86"
character_text_splitter = "0.1.2"
config = "0.15.8"
derive_builder = "0.20.2"
dotenv = "0.15.0"
futures = "0.3.31"
gset = "1.1.0"
reqwest = "0.12.12"
serde_derive = "1.0.218"
serde_json = "1.0.139"
thiserror = "2.0.11"
qdrant-client = "1.13.0"

# tracing
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
console-subscriber = "0.4.1"

# metrics dependencies
axum-prometheus = "0.8.0"
axum-tracing-opentelemetry = "0.26.1"
metrics-exporter-prometheus = "0.16.2"

[dependencies.axum]
version = "0.8.1"
features = ["multipart", "tracing", "tower-log"]

[dependencies.openai_dive]
version = "0.7.4"
features = ["stream"]

[dependencies.serde]
version = "1.0.218"
features = ["derive"]

[dependencies.tokio]
version = "1.43.0"
features = ["full"]

[dependencies.tower-http]
version = "0.6.2"
features = ["trace", "cors", "add-extension"]

[dependencies.utoipa]
version = "5.3.1"
features = ["axum_extras", "chrono"]

[dependencies.utoipa-rapidoc]
version = "6.0.0"
features = ["axum"]

[dependencies.uuid]
version = "1.15.0"
features = ["v4"]

[[bin]]
name = "rag"
path = "src/bin/launch_rag.rs"
